apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mattermost-data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
status:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  capacity:
    storage: 1Gi
  phase: Bound