apiVersion: v1
kind: Service
metadata:
  labels:
    app: mattermost-team-edition
  name: mattermost-team-edition
spec:
  ports:
    - name: 8065-tcp
      port: 8065
      protocol: TCP
      targetPort: 8065
    - name: 8067-tcp
      port: 8067
      protocol: TCP
      targetPort: 8067
    - name: 8074-tcp
      port: 8074
      protocol: TCP
      targetPort: 8074
    - name: 8075-tcp
      port: 8075
      protocol: TCP
      targetPort: 8075
  selector:
    deploymentconfig: mattermost-team-edition
  sessionAffinity: None
  type: ClusterIP